services:
  api-db:
    build: ./api-db
    ports:
      - "3309:3306"
    env_file:
      - api-db/.env
  api:
    build: ./api
    ports:
      - "9000:9000"
    volumes:
      - ./api:/app
    env_file:
      - ./api/.env
    command: npm start
    depends_on:
      - api-db